// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package githubcomdedaluslabsdedalussdkgo

import (
	"context"
	"encoding/json"
	"net/http"
	"slices"

	"github.com/dedalus-labs/dedalus-sdk-go/internal/apijson"
	shimjson "github.com/dedalus-labs/dedalus-sdk-go/internal/encoding/json"
	"github.com/dedalus-labs/dedalus-sdk-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-sdk-go/option"
	"github.com/dedalus-labs/dedalus-sdk-go/packages/param"
	"github.com/dedalus-labs/dedalus-sdk-go/packages/respjson"
)

// ImageService contains methods and other services that help with interacting with
// the Dedalus API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewImageService] method instead.
type ImageService struct {
	Options []option.RequestOption
}

// NewImageService generates a new service that applies the given options to each
// request. These options are applied after the parent client's options (if there
// is one), and before any request-specific options.
func NewImageService(opts ...option.RequestOption) (r ImageService) {
	r = ImageService{}
	r.Options = opts
	return
}

// Generate images from text prompts.
//
// Supports OpenAI (DALL-E, GPT Image) and Google (Nano Banana) models.
func (r *ImageService) Generate(ctx context.Context, body ImageGenerateParams, opts ...option.RequestOption) (res *ImagesResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/images/generations"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

// Request to generate images.
//
// The property Prompt is required.
type CreateImageRequestParam struct {
	// A text description of the desired image(s). The maximum length is 32000
	// characters for `gpt-image-1`, 1000 characters for `dall-e-2` and 4000 characters
	// for `dall-e-3`.
	Prompt string `json:"prompt,required"`
	// The model to use for image generation. One of `dall-e-2`, `dall-e-3`, or
	// `gpt-image-1`. Defaults to `dall-e-2` unless a parameter specific to
	// `gpt-image-1` is used.
	Model param.Opt[string] `json:"model,omitzero"`
	// The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only
	// `n=1` is supported.
	N param.Opt[int64] `json:"n,omitzero"`
	// The compression level (0-100%) for the generated images. This parameter is only
	// supported for `gpt-image-1` with the `webp` or `jpeg` output formats, and
	// defaults to 100.
	OutputCompression param.Opt[int64] `json:"output_compression,omitzero"`
	// The number of partial images to generate. This parameter is used for streaming
	// responses that return partial images. Value must be between 0 and 3. When set to
	// 0, the response will be a single image sent in one streaming event.
	//
	// Note that the final image may be sent before the full number of partial images
	// are generated if the full image is generated more quickly.
	PartialImages param.Opt[int64] `json:"partial_images,omitzero"`
	// Generate the image in streaming mode. Defaults to `false`. See the
	// [Image generation guide](https://platform.openai.com/docs/guides/image-generation)
	// for more information. This parameter is only supported for `gpt-image-1`.
	Stream param.Opt[bool] `json:"stream,omitzero"`
	// A unique identifier representing your end-user, which can help OpenAI to monitor
	// and detect abuse.
	// [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids).
	User param.Opt[string] `json:"user,omitzero"`
	// Allows to set transparency for the background of the generated image(s). This
	// parameter is only supported for `gpt-image-1`. Must be one of `transparent`,
	// `opaque` or `auto` (default value). When `auto` is used, the model will
	// automatically determine the best background for the image.
	//
	// If `transparent`, the output format needs to support transparency, so it should
	// be set to either `png` (default value) or `webp`.
	//
	// Any of "transparent", "opaque", "auto".
	Background CreateImageRequestBackground `json:"background,omitzero"`
	// Control the content-moderation level for images generated by `gpt-image-1`. Must
	// be either `low` for less restrictive filtering or `auto` (default value).
	//
	// Any of "low", "auto".
	Moderation CreateImageRequestModeration `json:"moderation,omitzero"`
	// The format in which the generated images are returned. This parameter is only
	// supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
	//
	// Any of "png", "jpeg", "webp".
	OutputFormat CreateImageRequestOutputFormat `json:"output_format,omitzero"`
	// The quality of the image that will be generated.
	//
	//   - `auto` (default value) will automatically select the best quality for the
	//     given model.
	//   - `high`, `medium` and `low` are supported for `gpt-image-1`.
	//   - `hd` and `standard` are supported for `dall-e-3`.
	//   - `standard` is the only option for `dall-e-2`.
	//
	// Any of "auto", "high", "medium", "low", "hd", "standard".
	Quality CreateImageRequestQuality `json:"quality,omitzero"`
	// The format in which generated images with `dall-e-2` and `dall-e-3` are
	// returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes
	// after the image has been generated. This parameter isn't supported for
	// `gpt-image-1` which will always return base64-encoded images.
	//
	// Any of "url", "b64_json".
	ResponseFormat CreateImageRequestResponseFormat `json:"response_format,omitzero"`
	// The size of the generated images. Must be one of `1024x1024`, `1536x1024`
	// (landscape), `1024x1536` (portrait), or `auto` (default value) for
	// `gpt-image-1`, one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and
	// one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3`.
	//
	// Any of "256x256", "512x512", "1024x1024", "1536x1024", "1024x1536", "1792x1024",
	// "1024x1792", "auto".
	Size CreateImageRequestSize `json:"size,omitzero"`
	// The style of the generated images. This parameter is only supported for
	// `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean
	// towards generating hyper-real and dramatic images. Natural causes the model to
	// produce more natural, less hyper-real looking images.
	//
	// Any of "vivid", "natural".
	Style CreateImageRequestStyle `json:"style,omitzero"`
	paramObj
}

func (r CreateImageRequestParam) MarshalJSON() (data []byte, err error) {
	type shadow CreateImageRequestParam
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *CreateImageRequestParam) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Allows to set transparency for the background of the generated image(s). This
// parameter is only supported for `gpt-image-1`. Must be one of `transparent`,
// `opaque` or `auto` (default value). When `auto` is used, the model will
// automatically determine the best background for the image.
//
// If `transparent`, the output format needs to support transparency, so it should
// be set to either `png` (default value) or `webp`.
type CreateImageRequestBackground string

const (
	CreateImageRequestBackgroundTransparent CreateImageRequestBackground = "transparent"
	CreateImageRequestBackgroundOpaque      CreateImageRequestBackground = "opaque"
	CreateImageRequestBackgroundAuto        CreateImageRequestBackground = "auto"
)

// Control the content-moderation level for images generated by `gpt-image-1`. Must
// be either `low` for less restrictive filtering or `auto` (default value).
type CreateImageRequestModeration string

const (
	CreateImageRequestModerationLow  CreateImageRequestModeration = "low"
	CreateImageRequestModerationAuto CreateImageRequestModeration = "auto"
)

// The format in which the generated images are returned. This parameter is only
// supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
type CreateImageRequestOutputFormat string

const (
	CreateImageRequestOutputFormatPng  CreateImageRequestOutputFormat = "png"
	CreateImageRequestOutputFormatJpeg CreateImageRequestOutputFormat = "jpeg"
	CreateImageRequestOutputFormatWebp CreateImageRequestOutputFormat = "webp"
)

// The quality of the image that will be generated.
//
//   - `auto` (default value) will automatically select the best quality for the
//     given model.
//   - `high`, `medium` and `low` are supported for `gpt-image-1`.
//   - `hd` and `standard` are supported for `dall-e-3`.
//   - `standard` is the only option for `dall-e-2`.
type CreateImageRequestQuality string

const (
	CreateImageRequestQualityAuto     CreateImageRequestQuality = "auto"
	CreateImageRequestQualityHigh     CreateImageRequestQuality = "high"
	CreateImageRequestQualityMedium   CreateImageRequestQuality = "medium"
	CreateImageRequestQualityLow      CreateImageRequestQuality = "low"
	CreateImageRequestQualityHD       CreateImageRequestQuality = "hd"
	CreateImageRequestQualityStandard CreateImageRequestQuality = "standard"
)

// The format in which generated images with `dall-e-2` and `dall-e-3` are
// returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes
// after the image has been generated. This parameter isn't supported for
// `gpt-image-1` which will always return base64-encoded images.
type CreateImageRequestResponseFormat string

const (
	CreateImageRequestResponseFormatURL     CreateImageRequestResponseFormat = "url"
	CreateImageRequestResponseFormatB64Json CreateImageRequestResponseFormat = "b64_json"
)

// The size of the generated images. Must be one of `1024x1024`, `1536x1024`
// (landscape), `1024x1536` (portrait), or `auto` (default value) for
// `gpt-image-1`, one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and
// one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3`.
type CreateImageRequestSize string

const (
	CreateImageRequestSize256x256   CreateImageRequestSize = "256x256"
	CreateImageRequestSize512x512   CreateImageRequestSize = "512x512"
	CreateImageRequestSize1024x1024 CreateImageRequestSize = "1024x1024"
	CreateImageRequestSize1536x1024 CreateImageRequestSize = "1536x1024"
	CreateImageRequestSize1024x1536 CreateImageRequestSize = "1024x1536"
	CreateImageRequestSize1792x1024 CreateImageRequestSize = "1792x1024"
	CreateImageRequestSize1024x1792 CreateImageRequestSize = "1024x1792"
	CreateImageRequestSizeAuto      CreateImageRequestSize = "auto"
)

// The style of the generated images. This parameter is only supported for
// `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean
// towards generating hyper-real and dramatic images. Natural causes the model to
// produce more natural, less hyper-real looking images.
type CreateImageRequestStyle string

const (
	CreateImageRequestStyleVivid   CreateImageRequestStyle = "vivid"
	CreateImageRequestStyleNatural CreateImageRequestStyle = "natural"
)

// Single image object.
type Image struct {
	// Base64-encoded image data (if response_format=b64_json)
	B64Json string `json:"b64_json,nullable"`
	// Revised prompt used for generation (dall-e-3)
	RevisedPrompt string `json:"revised_prompt,nullable"`
	// URL of the generated image (if response_format=url)
	URL string `json:"url,nullable"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		B64Json       respjson.Field
		RevisedPrompt respjson.Field
		URL           respjson.Field
		ExtraFields   map[string]respjson.Field
		raw           string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r Image) RawJSON() string { return r.JSON.raw }
func (r *Image) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Response from image generation.
type ImagesResponse struct {
	// Unix timestamp when images were created
	Created int64 `json:"created,required"`
	// List of generated images
	Data []Image `json:"data,required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Created     respjson.Field
		Data        respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ImagesResponse) RawJSON() string { return r.JSON.raw }
func (r *ImagesResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ImageGenerateParams struct {
	// Request to generate images.
	CreateImageRequest CreateImageRequestParam
	paramObj
}

func (r ImageGenerateParams) MarshalJSON() (data []byte, err error) {
	return shimjson.Marshal(r.CreateImageRequest)
}
func (r *ImageGenerateParams) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &r.CreateImageRequest)
}
