// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package githubcomdedaluslabsdedalussdkgo

import (
	"bytes"
	"context"
	"io"
	"mime/multipart"
	"net/http"
	"slices"

	"github.com/dedalus-labs/dedalus-sdk-go/internal/apiform"
	"github.com/dedalus-labs/dedalus-sdk-go/internal/apijson"
	"github.com/dedalus-labs/dedalus-sdk-go/internal/param"
	"github.com/dedalus-labs/dedalus-sdk-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-sdk-go/option"
)

// ImageService contains methods and other services that help with interacting with
// the Dedalus API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewImageService] method instead.
type ImageService struct {
	Options []option.RequestOption
}

// NewImageService generates a new service that applies the given options to each
// request. These options are applied after the parent client's options (if there
// is one), and before any request-specific options.
func NewImageService(opts ...option.RequestOption) (r *ImageService) {
	r = &ImageService{}
	r.Options = opts
	return
}

// Create variations of an image.
//
// DALL·E 2 only. Upload an image to generate variations.
func (r *ImageService) NewVariation(ctx context.Context, body ImageNewVariationParams, opts ...option.RequestOption) (res *ImagesResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/images/variations"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

// Edit images using inpainting.
//
// Supports dall-e-2 and gpt-image-1. Upload an image and optionally a mask to
// indicate which areas to regenerate based on the prompt.
func (r *ImageService) Edit(ctx context.Context, body ImageEditParams, opts ...option.RequestOption) (res *ImagesResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/images/edits"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

// Generate images from text prompts.
//
// Pure image generation models only (DALL-E, GPT Image). For multimodal models
// like gemini-2.5-flash-image, use /v1/chat/completions.
func (r *ImageService) Generate(ctx context.Context, body ImageGenerateParams, opts ...option.RequestOption) (res *ImagesResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/images/generations"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

// Request to generate images.
type CreateImageRequestParam struct {
	// A text description of the desired image(s). The maximum length is 32000
	// characters for `gpt-image-1`, 1000 characters for `dall-e-2` and 4000 characters
	// for `dall-e-3`.
	Prompt param.Field[string] `json:"prompt,required"`
	// Allows to set transparency for the background of the generated image(s). This
	// parameter is only supported for `gpt-image-1`. Must be one of `transparent`,
	// `opaque` or `auto` (default value). When `auto` is used, the model will
	// automatically determine the best background for the image.
	//
	// If `transparent`, the output format needs to support transparency, so it should
	// be set to either `png` (default value) or `webp`.
	Background param.Field[CreateImageRequestBackground] `json:"background"`
	// The model to use for image generation. One of `openai/dall-e-2`,
	// `openai/dall-e-3`, or `openai/gpt-image-1`. Defaults to `openai/dall-e-2` unless
	// a parameter specific to `gpt-image-1` is used.
	Model param.Field[string] `json:"model"`
	// Control the content-moderation level for images generated by `gpt-image-1`. Must
	// be either `low` for less restrictive filtering or `auto` (default value).
	Moderation param.Field[CreateImageRequestModeration] `json:"moderation"`
	// The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only
	// `n=1` is supported.
	N param.Field[int64] `json:"n"`
	// The compression level (0-100%) for the generated images. This parameter is only
	// supported for `gpt-image-1` with the `webp` or `jpeg` output formats, and
	// defaults to 100.
	OutputCompression param.Field[int64] `json:"output_compression"`
	// The format in which the generated images are returned. This parameter is only
	// supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
	OutputFormat param.Field[CreateImageRequestOutputFormat] `json:"output_format"`
	// The number of partial images to generate. This parameter is used for streaming
	// responses that return partial images. Value must be between 0 and 3. When set to
	// 0, the response will be a single image sent in one streaming event.
	//
	// Note that the final image may be sent before the full number of partial images
	// are generated if the full image is generated more quickly.
	PartialImages param.Field[int64] `json:"partial_images"`
	// The quality of the image that will be generated.
	//
	//   - `auto` (default value) will automatically select the best quality for the
	//     given model.
	//   - `high`, `medium` and `low` are supported for `gpt-image-1`.
	//   - `hd` and `standard` are supported for `dall-e-3`.
	//   - `standard` is the only option for `dall-e-2`.
	Quality param.Field[CreateImageRequestQuality] `json:"quality"`
	// The format in which generated images with `dall-e-2` and `dall-e-3` are
	// returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes
	// after the image has been generated. This parameter isn't supported for
	// `gpt-image-1` which will always return base64-encoded images.
	ResponseFormat param.Field[CreateImageRequestResponseFormat] `json:"response_format"`
	// The size of the generated images. Must be one of `1024x1024`, `1536x1024`
	// (landscape), `1024x1536` (portrait), or `auto` (default value) for
	// `gpt-image-1`, one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and
	// one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3`.
	Size param.Field[CreateImageRequestSize] `json:"size"`
	// Generate the image in streaming mode. Defaults to `false`. See the
	// [Image generation guide](https://platform.openai.com/docs/guides/image-generation)
	// for more information. This parameter is only supported for `gpt-image-1`.
	Stream param.Field[bool] `json:"stream"`
	// The style of the generated images. This parameter is only supported for
	// `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean
	// towards generating hyper-real and dramatic images. Natural causes the model to
	// produce more natural, less hyper-real looking images.
	Style param.Field[CreateImageRequestStyle] `json:"style"`
	// A unique identifier representing your end-user, which can help OpenAI to monitor
	// and detect abuse.
	// [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids).
	User param.Field[string] `json:"user"`
}

func (r CreateImageRequestParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

// Allows to set transparency for the background of the generated image(s). This
// parameter is only supported for `gpt-image-1`. Must be one of `transparent`,
// `opaque` or `auto` (default value). When `auto` is used, the model will
// automatically determine the best background for the image.
//
// If `transparent`, the output format needs to support transparency, so it should
// be set to either `png` (default value) or `webp`.
type CreateImageRequestBackground string

const (
	CreateImageRequestBackgroundTransparent CreateImageRequestBackground = "transparent"
	CreateImageRequestBackgroundOpaque      CreateImageRequestBackground = "opaque"
	CreateImageRequestBackgroundAuto        CreateImageRequestBackground = "auto"
)

func (r CreateImageRequestBackground) IsKnown() bool {
	switch r {
	case CreateImageRequestBackgroundTransparent, CreateImageRequestBackgroundOpaque, CreateImageRequestBackgroundAuto:
		return true
	}
	return false
}

// Control the content-moderation level for images generated by `gpt-image-1`. Must
// be either `low` for less restrictive filtering or `auto` (default value).
type CreateImageRequestModeration string

const (
	CreateImageRequestModerationLow  CreateImageRequestModeration = "low"
	CreateImageRequestModerationAuto CreateImageRequestModeration = "auto"
)

func (r CreateImageRequestModeration) IsKnown() bool {
	switch r {
	case CreateImageRequestModerationLow, CreateImageRequestModerationAuto:
		return true
	}
	return false
}

// The format in which the generated images are returned. This parameter is only
// supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
type CreateImageRequestOutputFormat string

const (
	CreateImageRequestOutputFormatPng  CreateImageRequestOutputFormat = "png"
	CreateImageRequestOutputFormatJpeg CreateImageRequestOutputFormat = "jpeg"
	CreateImageRequestOutputFormatWebp CreateImageRequestOutputFormat = "webp"
)

func (r CreateImageRequestOutputFormat) IsKnown() bool {
	switch r {
	case CreateImageRequestOutputFormatPng, CreateImageRequestOutputFormatJpeg, CreateImageRequestOutputFormatWebp:
		return true
	}
	return false
}

// The quality of the image that will be generated.
//
//   - `auto` (default value) will automatically select the best quality for the
//     given model.
//   - `high`, `medium` and `low` are supported for `gpt-image-1`.
//   - `hd` and `standard` are supported for `dall-e-3`.
//   - `standard` is the only option for `dall-e-2`.
type CreateImageRequestQuality string

const (
	CreateImageRequestQualityAuto     CreateImageRequestQuality = "auto"
	CreateImageRequestQualityHigh     CreateImageRequestQuality = "high"
	CreateImageRequestQualityMedium   CreateImageRequestQuality = "medium"
	CreateImageRequestQualityLow      CreateImageRequestQuality = "low"
	CreateImageRequestQualityHD       CreateImageRequestQuality = "hd"
	CreateImageRequestQualityStandard CreateImageRequestQuality = "standard"
)

func (r CreateImageRequestQuality) IsKnown() bool {
	switch r {
	case CreateImageRequestQualityAuto, CreateImageRequestQualityHigh, CreateImageRequestQualityMedium, CreateImageRequestQualityLow, CreateImageRequestQualityHD, CreateImageRequestQualityStandard:
		return true
	}
	return false
}

// The format in which generated images with `dall-e-2` and `dall-e-3` are
// returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes
// after the image has been generated. This parameter isn't supported for
// `gpt-image-1` which will always return base64-encoded images.
type CreateImageRequestResponseFormat string

const (
	CreateImageRequestResponseFormatURL     CreateImageRequestResponseFormat = "url"
	CreateImageRequestResponseFormatB64JSON CreateImageRequestResponseFormat = "b64_json"
)

func (r CreateImageRequestResponseFormat) IsKnown() bool {
	switch r {
	case CreateImageRequestResponseFormatURL, CreateImageRequestResponseFormatB64JSON:
		return true
	}
	return false
}

// The size of the generated images. Must be one of `1024x1024`, `1536x1024`
// (landscape), `1024x1536` (portrait), or `auto` (default value) for
// `gpt-image-1`, one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and
// one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3`.
type CreateImageRequestSize string

const (
	CreateImageRequestSize256x256   CreateImageRequestSize = "256x256"
	CreateImageRequestSize512x512   CreateImageRequestSize = "512x512"
	CreateImageRequestSize1024x1024 CreateImageRequestSize = "1024x1024"
	CreateImageRequestSize1536x1024 CreateImageRequestSize = "1536x1024"
	CreateImageRequestSize1024x1536 CreateImageRequestSize = "1024x1536"
	CreateImageRequestSize1792x1024 CreateImageRequestSize = "1792x1024"
	CreateImageRequestSize1024x1792 CreateImageRequestSize = "1024x1792"
	CreateImageRequestSizeAuto      CreateImageRequestSize = "auto"
)

func (r CreateImageRequestSize) IsKnown() bool {
	switch r {
	case CreateImageRequestSize256x256, CreateImageRequestSize512x512, CreateImageRequestSize1024x1024, CreateImageRequestSize1536x1024, CreateImageRequestSize1024x1536, CreateImageRequestSize1792x1024, CreateImageRequestSize1024x1792, CreateImageRequestSizeAuto:
		return true
	}
	return false
}

// The style of the generated images. This parameter is only supported for
// `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean
// towards generating hyper-real and dramatic images. Natural causes the model to
// produce more natural, less hyper-real looking images.
type CreateImageRequestStyle string

const (
	CreateImageRequestStyleVivid   CreateImageRequestStyle = "vivid"
	CreateImageRequestStyleNatural CreateImageRequestStyle = "natural"
)

func (r CreateImageRequestStyle) IsKnown() bool {
	switch r {
	case CreateImageRequestStyleVivid, CreateImageRequestStyleNatural:
		return true
	}
	return false
}

// Single image object.
type Image struct {
	// Base64-encoded image data (if response_format=b64_json)
	B64JSON string `json:"b64_json,nullable"`
	// Revised prompt used for generation (dall-e-3)
	RevisedPrompt string `json:"revised_prompt,nullable"`
	// URL of the generated image (if response_format=url)
	URL  string    `json:"url,nullable"`
	JSON imageJSON `json:"-"`
}

// imageJSON contains the JSON metadata for the struct [Image]
type imageJSON struct {
	B64JSON       apijson.Field
	RevisedPrompt apijson.Field
	URL           apijson.Field
	raw           string
	ExtraFields   map[string]apijson.Field
}

func (r *Image) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r imageJSON) RawJSON() string {
	return r.raw
}

// Response from image generation.
type ImagesResponse struct {
	// Unix timestamp when images were created
	Created int64 `json:"created,required"`
	// List of generated images
	Data []Image            `json:"data,required"`
	JSON imagesResponseJSON `json:"-"`
}

// imagesResponseJSON contains the JSON metadata for the struct [ImagesResponse]
type imagesResponseJSON struct {
	Created     apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ImagesResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r imagesResponseJSON) RawJSON() string {
	return r.raw
}

type ImageNewVariationParams struct {
	Image          param.Field[io.Reader] `json:"image,required" format:"binary"`
	Model          param.Field[string]    `json:"model"`
	N              param.Field[int64]     `json:"n"`
	ResponseFormat param.Field[string]    `json:"response_format"`
	Size           param.Field[string]    `json:"size"`
	User           param.Field[string]    `json:"user"`
}

func (r ImageNewVariationParams) MarshalMultipart() (data []byte, contentType string, err error) {
	buf := bytes.NewBuffer(nil)
	writer := multipart.NewWriter(buf)
	err = apiform.MarshalRoot(r, writer)
	if err != nil {
		writer.Close()
		return nil, "", err
	}
	err = writer.Close()
	if err != nil {
		return nil, "", err
	}
	return buf.Bytes(), writer.FormDataContentType(), nil
}

type ImageEditParams struct {
	Image          param.Field[io.Reader] `json:"image,required" format:"binary"`
	Prompt         param.Field[string]    `json:"prompt,required"`
	Mask           param.Field[io.Reader] `json:"mask" format:"binary"`
	Model          param.Field[string]    `json:"model"`
	N              param.Field[int64]     `json:"n"`
	ResponseFormat param.Field[string]    `json:"response_format"`
	Size           param.Field[string]    `json:"size"`
	User           param.Field[string]    `json:"user"`
}

func (r ImageEditParams) MarshalMultipart() (data []byte, contentType string, err error) {
	buf := bytes.NewBuffer(nil)
	writer := multipart.NewWriter(buf)
	err = apiform.MarshalRoot(r, writer)
	if err != nil {
		writer.Close()
		return nil, "", err
	}
	err = writer.Close()
	if err != nil {
		return nil, "", err
	}
	return buf.Bytes(), writer.FormDataContentType(), nil
}

type ImageGenerateParams struct {
	// Request to generate images.
	CreateImageRequest CreateImageRequestParam `json:"create_image_request,required"`
}

func (r ImageGenerateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.CreateImageRequest)
}
